// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtoProtocol.proto

package netty.demo.protobuf;

public final class ProtoProtocolProto {
  private ProtoProtocolProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code proto.ProtocolTag}
   */
  public enum ProtocolTag
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>Req = 1;</code>
     */
    Req(1),
    /**
     * <code>Resp = 2;</code>
     */
    Resp(2),
    ;

    /**
     * <code>Req = 1;</code>
     */
    public static final int Req_VALUE = 1;
    /**
     * <code>Resp = 2;</code>
     */
    public static final int Resp_VALUE = 2;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static ProtocolTag valueOf(int value) {
      return forNumber(value);
    }

    public static ProtocolTag forNumber(int value) {
      switch (value) {
        case 1: return Req;
        case 2: return Resp;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ProtocolTag>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ProtocolTag> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ProtocolTag>() {
            public ProtocolTag findValueByNumber(int number) {
              return ProtocolTag.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return netty.demo.protobuf.ProtoProtocolProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final ProtocolTag[] VALUES = values();

    public static ProtocolTag valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ProtocolTag(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:proto.ProtocolTag)
  }

  public interface ProtoProtocolOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.ProtoProtocol)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .proto.ProtocolTag type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>required .proto.ProtocolTag type = 1;</code>
     */
    netty.demo.protobuf.ProtoProtocolProto.ProtocolTag getType();

    /**
     * <code>optional .proto.SubscribeReq subReq = 2;</code>
     */
    boolean hasSubReq();
    /**
     * <code>optional .proto.SubscribeReq subReq = 2;</code>
     */
    SubscribeReqProto.SubscribeReq getSubReq();
    /**
     * <code>optional .proto.SubscribeReq subReq = 2;</code>
     */
    SubscribeReqProto.SubscribeReqOrBuilder getSubReqOrBuilder();

    /**
     * <code>optional .proto.SubscribeResp subResp = 3;</code>
     */
    boolean hasSubResp();
    /**
     * <code>optional .proto.SubscribeResp subResp = 3;</code>
     */
    SubscribeRespProto.SubscribeResp getSubResp();
    /**
     * <code>optional .proto.SubscribeResp subResp = 3;</code>
     */
    SubscribeRespProto.SubscribeRespOrBuilder getSubRespOrBuilder();
  }
  /**
   * Protobuf type {@code proto.ProtoProtocol}
   */
  public  static final class ProtoProtocol extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.ProtoProtocol)
      ProtoProtocolOrBuilder {
    // Use ProtoProtocol.newBuilder() to construct.
    private ProtoProtocol(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ProtoProtocol() {
      type_ = 1;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ProtoProtocol(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              netty.demo.protobuf.ProtoProtocolProto.ProtocolTag value = netty.demo.protobuf.ProtoProtocolProto.ProtocolTag.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = rawValue;
              }
              break;
            }
            case 18: {
              SubscribeReqProto.SubscribeReq.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = subReq_.toBuilder();
              }
              subReq_ = input.readMessage(SubscribeReqProto.SubscribeReq.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(subReq_);
                subReq_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 26: {
              SubscribeRespProto.SubscribeResp.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = subResp_.toBuilder();
              }
              subResp_ = input.readMessage(SubscribeRespProto.SubscribeResp.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(subResp_);
                subResp_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return netty.demo.protobuf.ProtoProtocolProto.internal_static_proto_ProtoProtocol_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return netty.demo.protobuf.ProtoProtocolProto.internal_static_proto_ProtoProtocol_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              netty.demo.protobuf.ProtoProtocolProto.ProtoProtocol.class, netty.demo.protobuf.ProtoProtocolProto.ProtoProtocol.Builder.class);
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>required .proto.ProtocolTag type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .proto.ProtocolTag type = 1;</code>
     */
    public netty.demo.protobuf.ProtoProtocolProto.ProtocolTag getType() {
      netty.demo.protobuf.ProtoProtocolProto.ProtocolTag result = netty.demo.protobuf.ProtoProtocolProto.ProtocolTag.valueOf(type_);
      return result == null ? netty.demo.protobuf.ProtoProtocolProto.ProtocolTag.Req : result;
    }

    public static final int SUBREQ_FIELD_NUMBER = 2;
    private SubscribeReqProto.SubscribeReq subReq_;
    /**
     * <code>optional .proto.SubscribeReq subReq = 2;</code>
     */
    public boolean hasSubReq() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .proto.SubscribeReq subReq = 2;</code>
     */
    public SubscribeReqProto.SubscribeReq getSubReq() {
      return subReq_ == null ? SubscribeReqProto.SubscribeReq.getDefaultInstance() : subReq_;
    }
    /**
     * <code>optional .proto.SubscribeReq subReq = 2;</code>
     */
    public SubscribeReqProto.SubscribeReqOrBuilder getSubReqOrBuilder() {
      return subReq_ == null ? SubscribeReqProto.SubscribeReq.getDefaultInstance() : subReq_;
    }

    public static final int SUBRESP_FIELD_NUMBER = 3;
    private SubscribeRespProto.SubscribeResp subResp_;
    /**
     * <code>optional .proto.SubscribeResp subResp = 3;</code>
     */
    public boolean hasSubResp() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .proto.SubscribeResp subResp = 3;</code>
     */
    public SubscribeRespProto.SubscribeResp getSubResp() {
      return subResp_ == null ? SubscribeRespProto.SubscribeResp.getDefaultInstance() : subResp_;
    }
    /**
     * <code>optional .proto.SubscribeResp subResp = 3;</code>
     */
    public SubscribeRespProto.SubscribeRespOrBuilder getSubRespOrBuilder() {
      return subResp_ == null ? SubscribeRespProto.SubscribeResp.getDefaultInstance() : subResp_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasSubReq()) {
        if (!getSubReq().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasSubResp()) {
        if (!getSubResp().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, getSubReq());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, getSubResp());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getSubReq());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getSubResp());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof netty.demo.protobuf.ProtoProtocolProto.ProtoProtocol)) {
        return super.equals(obj);
      }
      netty.demo.protobuf.ProtoProtocolProto.ProtoProtocol other = (netty.demo.protobuf.ProtoProtocolProto.ProtoProtocol) obj;

      boolean result = true;
      result = result && (hasType() == other.hasType());
      if (hasType()) {
        result = result && type_ == other.type_;
      }
      result = result && (hasSubReq() == other.hasSubReq());
      if (hasSubReq()) {
        result = result && getSubReq()
            .equals(other.getSubReq());
      }
      result = result && (hasSubResp() == other.hasSubResp());
      if (hasSubResp()) {
        result = result && getSubResp()
            .equals(other.getSubResp());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + type_;
      }
      if (hasSubReq()) {
        hash = (37 * hash) + SUBREQ_FIELD_NUMBER;
        hash = (53 * hash) + getSubReq().hashCode();
      }
      if (hasSubResp()) {
        hash = (37 * hash) + SUBRESP_FIELD_NUMBER;
        hash = (53 * hash) + getSubResp().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static netty.demo.protobuf.ProtoProtocolProto.ProtoProtocol parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static netty.demo.protobuf.ProtoProtocolProto.ProtoProtocol parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static netty.demo.protobuf.ProtoProtocolProto.ProtoProtocol parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static netty.demo.protobuf.ProtoProtocolProto.ProtoProtocol parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static netty.demo.protobuf.ProtoProtocolProto.ProtoProtocol parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static netty.demo.protobuf.ProtoProtocolProto.ProtoProtocol parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static netty.demo.protobuf.ProtoProtocolProto.ProtoProtocol parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static netty.demo.protobuf.ProtoProtocolProto.ProtoProtocol parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static netty.demo.protobuf.ProtoProtocolProto.ProtoProtocol parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static netty.demo.protobuf.ProtoProtocolProto.ProtoProtocol parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(netty.demo.protobuf.ProtoProtocolProto.ProtoProtocol prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.ProtoProtocol}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.ProtoProtocol)
        netty.demo.protobuf.ProtoProtocolProto.ProtoProtocolOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return netty.demo.protobuf.ProtoProtocolProto.internal_static_proto_ProtoProtocol_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return netty.demo.protobuf.ProtoProtocolProto.internal_static_proto_ProtoProtocol_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                netty.demo.protobuf.ProtoProtocolProto.ProtoProtocol.class, netty.demo.protobuf.ProtoProtocolProto.ProtoProtocol.Builder.class);
      }

      // Construct using netty.demo.protobuf.ProtoProtocolProto.ProtoProtocol.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getSubReqFieldBuilder();
          getSubRespFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        type_ = 1;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (subReqBuilder_ == null) {
          subReq_ = null;
        } else {
          subReqBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        if (subRespBuilder_ == null) {
          subResp_ = null;
        } else {
          subRespBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return netty.demo.protobuf.ProtoProtocolProto.internal_static_proto_ProtoProtocol_descriptor;
      }

      public netty.demo.protobuf.ProtoProtocolProto.ProtoProtocol getDefaultInstanceForType() {
        return netty.demo.protobuf.ProtoProtocolProto.ProtoProtocol.getDefaultInstance();
      }

      public netty.demo.protobuf.ProtoProtocolProto.ProtoProtocol build() {
        netty.demo.protobuf.ProtoProtocolProto.ProtoProtocol result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public netty.demo.protobuf.ProtoProtocolProto.ProtoProtocol buildPartial() {
        netty.demo.protobuf.ProtoProtocolProto.ProtoProtocol result = new netty.demo.protobuf.ProtoProtocolProto.ProtoProtocol(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (subReqBuilder_ == null) {
          result.subReq_ = subReq_;
        } else {
          result.subReq_ = subReqBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (subRespBuilder_ == null) {
          result.subResp_ = subResp_;
        } else {
          result.subResp_ = subRespBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof netty.demo.protobuf.ProtoProtocolProto.ProtoProtocol) {
          return mergeFrom((netty.demo.protobuf.ProtoProtocolProto.ProtoProtocol)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(netty.demo.protobuf.ProtoProtocolProto.ProtoProtocol other) {
        if (other == netty.demo.protobuf.ProtoProtocolProto.ProtoProtocol.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasSubReq()) {
          mergeSubReq(other.getSubReq());
        }
        if (other.hasSubResp()) {
          mergeSubResp(other.getSubResp());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          return false;
        }
        if (hasSubReq()) {
          if (!getSubReq().isInitialized()) {
            return false;
          }
        }
        if (hasSubResp()) {
          if (!getSubResp().isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        netty.demo.protobuf.ProtoProtocolProto.ProtoProtocol parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (netty.demo.protobuf.ProtoProtocolProto.ProtoProtocol) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int type_ = 1;
      /**
       * <code>required .proto.ProtocolTag type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .proto.ProtocolTag type = 1;</code>
       */
      public netty.demo.protobuf.ProtoProtocolProto.ProtocolTag getType() {
        netty.demo.protobuf.ProtoProtocolProto.ProtocolTag result = netty.demo.protobuf.ProtoProtocolProto.ProtocolTag.valueOf(type_);
        return result == null ? netty.demo.protobuf.ProtoProtocolProto.ProtocolTag.Req : result;
      }
      /**
       * <code>required .proto.ProtocolTag type = 1;</code>
       */
      public Builder setType(netty.demo.protobuf.ProtoProtocolProto.ProtocolTag value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .proto.ProtocolTag type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 1;
        onChanged();
        return this;
      }

      private SubscribeReqProto.SubscribeReq subReq_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          SubscribeReqProto.SubscribeReq, SubscribeReqProto.SubscribeReq.Builder, SubscribeReqProto.SubscribeReqOrBuilder> subReqBuilder_;
      /**
       * <code>optional .proto.SubscribeReq subReq = 2;</code>
       */
      public boolean hasSubReq() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .proto.SubscribeReq subReq = 2;</code>
       */
      public SubscribeReqProto.SubscribeReq getSubReq() {
        if (subReqBuilder_ == null) {
          return subReq_ == null ? SubscribeReqProto.SubscribeReq.getDefaultInstance() : subReq_;
        } else {
          return subReqBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .proto.SubscribeReq subReq = 2;</code>
       */
      public Builder setSubReq(SubscribeReqProto.SubscribeReq value) {
        if (subReqBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          subReq_ = value;
          onChanged();
        } else {
          subReqBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .proto.SubscribeReq subReq = 2;</code>
       */
      public Builder setSubReq(
          SubscribeReqProto.SubscribeReq.Builder builderForValue) {
        if (subReqBuilder_ == null) {
          subReq_ = builderForValue.build();
          onChanged();
        } else {
          subReqBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .proto.SubscribeReq subReq = 2;</code>
       */
      public Builder mergeSubReq(SubscribeReqProto.SubscribeReq value) {
        if (subReqBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              subReq_ != null &&
              subReq_ != SubscribeReqProto.SubscribeReq.getDefaultInstance()) {
            subReq_ =
              SubscribeReqProto.SubscribeReq.newBuilder(subReq_).mergeFrom(value).buildPartial();
          } else {
            subReq_ = value;
          }
          onChanged();
        } else {
          subReqBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .proto.SubscribeReq subReq = 2;</code>
       */
      public Builder clearSubReq() {
        if (subReqBuilder_ == null) {
          subReq_ = null;
          onChanged();
        } else {
          subReqBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .proto.SubscribeReq subReq = 2;</code>
       */
      public SubscribeReqProto.SubscribeReq.Builder getSubReqBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getSubReqFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .proto.SubscribeReq subReq = 2;</code>
       */
      public SubscribeReqProto.SubscribeReqOrBuilder getSubReqOrBuilder() {
        if (subReqBuilder_ != null) {
          return subReqBuilder_.getMessageOrBuilder();
        } else {
          return subReq_ == null ?
              SubscribeReqProto.SubscribeReq.getDefaultInstance() : subReq_;
        }
      }
      /**
       * <code>optional .proto.SubscribeReq subReq = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          SubscribeReqProto.SubscribeReq, SubscribeReqProto.SubscribeReq.Builder, SubscribeReqProto.SubscribeReqOrBuilder>
          getSubReqFieldBuilder() {
        if (subReqBuilder_ == null) {
          subReqBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              SubscribeReqProto.SubscribeReq, SubscribeReqProto.SubscribeReq.Builder, SubscribeReqProto.SubscribeReqOrBuilder>(
                  getSubReq(),
                  getParentForChildren(),
                  isClean());
          subReq_ = null;
        }
        return subReqBuilder_;
      }

      private SubscribeRespProto.SubscribeResp subResp_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          SubscribeRespProto.SubscribeResp, SubscribeRespProto.SubscribeResp.Builder, SubscribeRespProto.SubscribeRespOrBuilder> subRespBuilder_;
      /**
       * <code>optional .proto.SubscribeResp subResp = 3;</code>
       */
      public boolean hasSubResp() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .proto.SubscribeResp subResp = 3;</code>
       */
      public SubscribeRespProto.SubscribeResp getSubResp() {
        if (subRespBuilder_ == null) {
          return subResp_ == null ? SubscribeRespProto.SubscribeResp.getDefaultInstance() : subResp_;
        } else {
          return subRespBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .proto.SubscribeResp subResp = 3;</code>
       */
      public Builder setSubResp(SubscribeRespProto.SubscribeResp value) {
        if (subRespBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          subResp_ = value;
          onChanged();
        } else {
          subRespBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .proto.SubscribeResp subResp = 3;</code>
       */
      public Builder setSubResp(
          SubscribeRespProto.SubscribeResp.Builder builderForValue) {
        if (subRespBuilder_ == null) {
          subResp_ = builderForValue.build();
          onChanged();
        } else {
          subRespBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .proto.SubscribeResp subResp = 3;</code>
       */
      public Builder mergeSubResp(SubscribeRespProto.SubscribeResp value) {
        if (subRespBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              subResp_ != null &&
              subResp_ != SubscribeRespProto.SubscribeResp.getDefaultInstance()) {
            subResp_ =
              SubscribeRespProto.SubscribeResp.newBuilder(subResp_).mergeFrom(value).buildPartial();
          } else {
            subResp_ = value;
          }
          onChanged();
        } else {
          subRespBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .proto.SubscribeResp subResp = 3;</code>
       */
      public Builder clearSubResp() {
        if (subRespBuilder_ == null) {
          subResp_ = null;
          onChanged();
        } else {
          subRespBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .proto.SubscribeResp subResp = 3;</code>
       */
      public SubscribeRespProto.SubscribeResp.Builder getSubRespBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getSubRespFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .proto.SubscribeResp subResp = 3;</code>
       */
      public SubscribeRespProto.SubscribeRespOrBuilder getSubRespOrBuilder() {
        if (subRespBuilder_ != null) {
          return subRespBuilder_.getMessageOrBuilder();
        } else {
          return subResp_ == null ?
              SubscribeRespProto.SubscribeResp.getDefaultInstance() : subResp_;
        }
      }
      /**
       * <code>optional .proto.SubscribeResp subResp = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          SubscribeRespProto.SubscribeResp, SubscribeRespProto.SubscribeResp.Builder, SubscribeRespProto.SubscribeRespOrBuilder>
          getSubRespFieldBuilder() {
        if (subRespBuilder_ == null) {
          subRespBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              SubscribeRespProto.SubscribeResp, SubscribeRespProto.SubscribeResp.Builder, SubscribeRespProto.SubscribeRespOrBuilder>(
                  getSubResp(),
                  getParentForChildren(),
                  isClean());
          subResp_ = null;
        }
        return subRespBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.ProtoProtocol)
    }

    // @@protoc_insertion_point(class_scope:proto.ProtoProtocol)
    private static final netty.demo.protobuf.ProtoProtocolProto.ProtoProtocol DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new netty.demo.protobuf.ProtoProtocolProto.ProtoProtocol();
    }

    public static netty.demo.protobuf.ProtoProtocolProto.ProtoProtocol getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<ProtoProtocol>
        PARSER = new com.google.protobuf.AbstractParser<ProtoProtocol>() {
      public ProtoProtocol parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ProtoProtocol(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ProtoProtocol> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ProtoProtocol> getParserForType() {
      return PARSER;
    }

    public netty.demo.protobuf.ProtoProtocolProto.ProtoProtocol getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_ProtoProtocol_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_ProtoProtocol_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\023ProtoProtocol.proto\022\005proto\032\022SubscribeR" +
      "eq.proto\032\023SubscribeResp.proto\"}\n\rProtoPr" +
      "otocol\022 \n\004type\030\001 \002(\0162\022.proto.ProtocolTag" +
      "\022#\n\006subReq\030\002 \001(\0132\023.proto.SubscribeReq\022%\n" +
      "\007subResp\030\003 \001(\0132\024.proto.SubscribeResp* \n\013" +
      "ProtocolTag\022\007\n\003Req\020\001\022\010\n\004Resp\020\002B)\n\023netty." +
      "demo.protobufB\022ProtoProtocolProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          SubscribeReqProto.getDescriptor(),
          SubscribeRespProto.getDescriptor(),
        }, assigner);
    internal_static_proto_ProtoProtocol_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_ProtoProtocol_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_ProtoProtocol_descriptor,
        new String[] { "Type", "SubReq", "SubResp", });
    SubscribeReqProto.getDescriptor();
    SubscribeRespProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
